name: seclot
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.1+2

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  intl: ^0.15.7

#environment:
#  sdk: ">=1.9.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.0+15
  shared_preferences: ^0.5.3+2
  flutter_spinkit: ^3.1.0
  provider: ^3.0.0+1
  http: ^0.12.0+2
  sqflite: ^1.1.6+1
  fluttertoast: ^3.1.0
  dio: ^2.1.13
#  google_places_picker: ^0.0.9
  flutter_paystack: ^1.0.1
  image: ^2.1.4
  clippy: ^1.0.0
  flutter_places_dialog: ^1.0.5
#  paystack_sdk: ^0.0.1
  intl: ^0.15.8
  flutter_masked_text: ^0.8.0
  scoped_model: ^1.0.1
  http_parser: ^3.1.3
  cached_network_image: ^1.1.0
  flutter_advanced_networkimage: ^0.5.0
  flutter_launcher_icons: "^0.7.0"
  flutter_image: ^2.0.0
  location: any
  permission: ^0.1.2

  firebase_core: ^0.4.0+8
  firebase_messaging: ^5.1.2

#  onesignal_flutter: ^2.0.1
  cloud_firestore: ^0.12.7+1
  firebase_database: ^3.0.5
  rxdart: ^0.22.1

  location_permissions: ^2.0.2

  eva_icons_flutter: ^2.0.0

#
dev_dependencies:
#  flutter_test:
#    sdk: flutter

  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resources/icon/logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
  - resources/images/
#    - resources/images/logo.jpeg
#    - resources/images/home_phone.png
#    - resources/images/nav_header_background.png
#    - resources/images/home.png
#    - resources/images/magic_wand.png
#    - resources/images/wallet.png
#    - resources/images/history.png
#    - resources/images/visa_card.png
#    - resources/images/master_card.png
#    - resources/images/bronze_indicator.png
#    - resources/images/check.png
#    - resources/images/login_image.png
#    - resources/images/otp.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
